### ISSUE TITLE
Fetching Price hangs on Vision AI+

### ISSUE THREAD

**Issue by mondycarter** [Marksdo/VisionAI#1]
I'd like to buy the app but I can't because it won't stop fetching the price. 

![Screenshot 2023-06-06 at 1 19 04 PM](https://github.com/Marksdo/VisionAI/assets/135735875/690fb02d-eb71-4964-86ff-9081ead4f50a)

**Comment by Marksdo** [comment]
Please wait a 2-3 days, i will change the fetching price features. Sorry about the issue.

**Comment by mondycarter** [comment]
反応に感謝します、ありがとう Sent from my iPhoneOn Jun 7, 2023, at 7:43 AM, 荒野求声 ***@***.***> wrote:﻿
Please wait a 2-3 days, i will change the fetching price features. Sorry about the issue.
